-- ============================================================
-- Datei: farbe_insert_simis1.sql
-- Zweck: Beispieldaten fuer Tabelle FARBE (Premium-Moebelhaus)
-- Spalten: FARBENID, BEZEICHNUNG, HEXCODE (ohne #, genau 6 Zeichen)
-- Hinweis: Keine Sonderzeichen (keine Umlaute/ss).
-- ============================================================

-- Optional: Tabelle leeren (nur ausfuehren, wenn gewuenscht)
-- DELETE FROM FARBE;
-- COMMIT;

INSERT ALL
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (1,  'Weiss',        'FFFFFF')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (2,  'Schwarz',      '000000')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (3,  'Anthrazit',    '2F2F2F')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (4,  'Graphit',      '3A3A3A')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (5,  'Grau',         'A9A9A9')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (6,  'Hellgrau',     'D3D3D3')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (7,  'Creme',        'F5F0E6')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (8,  'Beige',        'D6C7B2')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (9,  'Sand',         'C2B280')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (10, 'Taupe',        '8B7D6B')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (11, 'Braun',        '6B4F3A')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (12, 'Eiche Hell',   'C9A66B')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (13, 'Eiche Dunkel', '8B5A2B')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (14, 'Nussbaum',     '5C3A21')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (15, 'Teak',         '996633')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (16, 'Mahagoni',     '7A2E2E')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (17, 'Bordeaux',     '4A0E1A')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (18, 'Rot',          '8B0000')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (19, 'Senfgelb',     'C9A227')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (20, 'Gold',         'B08D57')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (21, 'Silber',       'C0C0C0')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (22, 'Kupfer',       'B87333')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (23, 'Bronze',       'CD7F32')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (24, 'Blau',         '1E4F8A')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (25, 'Navy',         '0B1F3A')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (26, 'Petrol',       '006B6B')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (27, 'Gruen',        '2E6B3A')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (28, 'Oliv',         '556B2F')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (29, 'Rosa',         'D98CA3')
  INTO FARBE (FARBENID, BEZEICHNUNG, HEXCODE) VALUES (30, 'Champagner',   'F7E7CE')
SELECT 1 FROM DUAL;

COMMIT;
