-- ============================================================
-- Datei: lager_insert_simis1.sql
-- Zweck: Beispieldaten fuer Tabelle LAGER
-- Abhaengigkeiten: BESTELLUNG (BESTELLUNGID 1..600) muss vorhanden sein.
-- Format: Einzel-INSERTs (SQL*Plus kompatibel)
-- Hinweis: Keine Sonderzeichen.
-- Tabelle: LAGER(LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
-- ============================================================

-- Optional: Tabelle leeren (nur ausfuehren, wenn gewuenscht)
-- DELETE FROM LAGER;
-- COMMIT;

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (1, 1, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (2, 2, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (3, 3, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (4, 4, 35);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (5, 5, 22);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (6, 6, 33);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (7, 7, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (8, 8, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (9, 9, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (10, 10, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (11, 11, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (12, 12, 20);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (13, 13, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (14, 14, 19);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (15, 15, 25);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (16, 16, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (17, 17, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (18, 18, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (19, 19, 18);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (20, 20, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (21, 21, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (22, 22, 17);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (23, 23, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (24, 24, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (25, 25, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (26, 26, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (27, 27, 13);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (28, 28, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (29, 29, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (30, 30, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (31, 31, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (32, 32, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (33, 33, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (34, 34, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (35, 35, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (36, 36, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (37, 37, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (38, 38, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (39, 39, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (40, 40, 13);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (41, 41, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (42, 42, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (43, 43, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (44, 44, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (45, 45, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (46, 46, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (47, 47, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (48, 48, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (49, 49, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (50, 50, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (51, 51, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (52, 52, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (53, 53, 25);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (54, 54, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (55, 55, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (56, 56, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (57, 57, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (58, 58, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (59, 59, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (60, 60, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (61, 61, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (62, 62, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (63, 63, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (64, 64, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (65, 65, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (66, 66, 19);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (67, 67, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (68, 68, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (69, 69, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (70, 70, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (71, 71, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (72, 72, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (73, 73, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (74, 74, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (75, 75, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (76, 76, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (77, 77, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (78, 78, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (79, 79, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (80, 80, 16);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (81, 81, 13);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (82, 82, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (83, 83, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (84, 84, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (85, 85, 11);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (86, 86, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (87, 87, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (88, 88, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (89, 89, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (90, 90, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (91, 91, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (92, 92, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (93, 93, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (94, 94, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (95, 95, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (96, 96, 15);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (97, 97, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (98, 98, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (99, 99, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (100, 100, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (101, 101, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (102, 102, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (103, 103, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (104, 104, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (105, 105, 11);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (106, 106, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (107, 107, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (108, 108, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (109, 109, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (110, 110, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (111, 111, 19);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (112, 112, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (113, 113, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (114, 114, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (115, 115, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (116, 116, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (117, 117, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (118, 118, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (119, 119, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (120, 120, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (121, 121, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (122, 122, 54);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (123, 123, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (124, 124, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (125, 125, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (126, 126, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (127, 127, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (128, 128, 32);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (129, 129, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (130, 130, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (131, 131, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (132, 132, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (133, 133, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (134, 134, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (135, 135, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (136, 136, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (137, 137, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (138, 138, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (139, 139, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (140, 140, 28);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (141, 141, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (142, 142, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (143, 143, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (144, 144, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (145, 145, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (146, 146, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (147, 147, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (148, 148, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (149, 149, 22);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (150, 150, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (151, 151, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (152, 152, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (153, 153, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (154, 154, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (155, 155, 15);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (156, 156, 15);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (157, 157, 18);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (158, 158, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (159, 159, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (160, 160, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (161, 161, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (162, 162, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (163, 163, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (164, 164, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (165, 165, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (166, 166, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (167, 167, 18);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (168, 168, 25);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (169, 169, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (170, 170, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (171, 171, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (172, 172, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (173, 173, 17);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (174, 174, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (175, 175, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (176, 176, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (177, 177, 24);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (178, 178, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (179, 179, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (180, 180, 25);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (181, 181, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (182, 182, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (183, 183, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (184, 184, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (185, 185, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (186, 186, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (187, 187, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (188, 188, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (189, 189, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (190, 190, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (191, 191, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (192, 192, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (193, 193, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (194, 194, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (195, 195, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (196, 196, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (197, 197, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (198, 198, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (199, 199, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (200, 200, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (201, 201, 33);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (202, 202, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (203, 203, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (204, 204, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (205, 205, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (206, 206, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (207, 207, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (208, 208, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (209, 209, 18);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (210, 210, 23);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (211, 211, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (212, 212, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (213, 213, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (214, 214, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (215, 215, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (216, 216, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (217, 217, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (218, 218, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (219, 219, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (220, 220, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (221, 221, 17);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (222, 222, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (223, 223, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (224, 224, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (225, 225, 13);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (226, 226, 22);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (227, 227, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (228, 228, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (229, 229, 23);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (230, 230, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (231, 231, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (232, 232, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (233, 233, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (234, 234, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (235, 235, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (236, 236, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (237, 237, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (238, 238, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (239, 239, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (240, 240, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (241, 241, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (242, 242, 24);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (243, 243, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (244, 244, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (245, 245, 22);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (246, 246, 25);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (247, 247, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (248, 248, 23);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (249, 249, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (250, 250, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (251, 251, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (252, 252, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (253, 253, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (254, 254, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (255, 255, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (256, 256, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (257, 257, 29);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (258, 258, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (259, 259, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (260, 260, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (261, 261, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (262, 262, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (263, 263, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (264, 264, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (265, 265, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (266, 266, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (267, 267, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (268, 268, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (269, 269, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (270, 270, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (271, 271, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (272, 272, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (273, 273, 31);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (274, 274, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (275, 275, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (276, 276, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (277, 277, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (278, 278, 40);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (279, 279, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (280, 280, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (281, 281, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (282, 282, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (283, 283, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (284, 284, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (285, 285, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (286, 286, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (287, 287, 23);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (288, 288, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (289, 289, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (290, 290, 15);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (291, 291, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (292, 292, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (293, 293, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (294, 294, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (295, 295, 18);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (296, 296, 16);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (297, 297, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (298, 298, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (299, 299, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (300, 300, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (301, 301, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (302, 302, 12);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (303, 303, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (304, 304, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (305, 305, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (306, 306, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (307, 307, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (308, 308, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (309, 309, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (310, 310, 22);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (311, 311, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (312, 312, 12);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (313, 313, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (314, 314, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (315, 315, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (316, 316, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (317, 317, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (318, 318, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (319, 319, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (320, 320, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (321, 321, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (322, 322, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (323, 323, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (324, 324, 22);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (325, 325, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (326, 326, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (327, 327, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (328, 328, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (329, 329, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (330, 330, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (331, 331, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (332, 332, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (333, 333, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (334, 334, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (335, 335, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (336, 336, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (337, 337, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (338, 338, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (339, 339, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (340, 340, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (341, 341, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (342, 342, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (343, 343, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (344, 344, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (345, 345, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (346, 346, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (347, 347, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (348, 348, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (349, 349, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (350, 350, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (351, 351, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (352, 352, 14);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (353, 353, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (354, 354, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (355, 355, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (356, 356, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (357, 357, 20);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (358, 358, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (359, 359, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (360, 360, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (361, 361, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (362, 362, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (363, 363, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (364, 364, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (365, 365, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (366, 366, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (367, 367, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (368, 368, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (369, 369, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (370, 370, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (371, 371, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (372, 372, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (373, 373, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (374, 374, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (375, 375, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (376, 376, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (377, 377, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (378, 378, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (379, 379, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (380, 380, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (381, 381, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (382, 382, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (383, 383, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (384, 384, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (385, 385, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (386, 386, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (387, 387, 17);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (388, 388, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (389, 389, 23);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (390, 390, 18);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (391, 391, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (392, 392, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (393, 393, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (394, 394, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (395, 395, 18);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (396, 396, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (397, 397, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (398, 398, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (399, 399, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (400, 400, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (401, 401, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (402, 402, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (403, 403, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (404, 404, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (405, 405, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (406, 406, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (407, 407, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (408, 408, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (409, 409, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (410, 410, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (411, 411, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (412, 412, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (413, 413, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (414, 414, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (415, 415, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (416, 416, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (417, 417, 24);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (418, 418, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (419, 419, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (420, 420, 13);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (421, 421, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (422, 422, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (423, 423, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (424, 424, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (425, 425, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (426, 426, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (427, 427, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (428, 428, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (429, 429, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (430, 430, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (431, 431, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (432, 432, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (433, 433, 16);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (434, 434, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (435, 435, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (436, 436, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (437, 437, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (438, 438, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (439, 439, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (440, 440, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (441, 441, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (442, 442, 56);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (443, 443, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (444, 444, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (445, 445, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (446, 446, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (447, 447, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (448, 448, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (449, 449, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (450, 450, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (451, 451, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (452, 452, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (453, 453, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (454, 454, 12);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (455, 455, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (456, 456, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (457, 457, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (458, 458, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (459, 459, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (460, 460, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (461, 461, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (462, 462, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (463, 463, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (464, 464, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (465, 465, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (466, 466, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (467, 467, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (468, 468, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (469, 469, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (470, 470, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (471, 471, 24);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (472, 472, 26);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (473, 473, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (474, 474, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (475, 475, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (476, 476, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (477, 477, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (478, 478, 20);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (479, 479, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (480, 480, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (481, 481, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (482, 482, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (483, 483, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (484, 484, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (485, 485, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (486, 486, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (487, 487, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (488, 488, 11);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (489, 489, 42);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (490, 490, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (491, 491, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (492, 492, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (493, 493, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (494, 494, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (495, 495, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (496, 496, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (497, 497, 16);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (498, 498, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (499, 499, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (500, 500, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (501, 501, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (502, 502, 12);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (503, 503, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (504, 504, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (505, 505, 26);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (506, 506, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (507, 507, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (508, 508, 21);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (509, 509, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (510, 510, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (511, 511, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (512, 512, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (513, 513, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (514, 514, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (515, 515, 51);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (516, 516, 12);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (517, 517, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (518, 518, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (519, 519, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (520, 520, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (521, 521, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (522, 522, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (523, 523, 23);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (524, 524, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (525, 525, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (526, 526, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (527, 527, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (528, 528, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (529, 529, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (530, 530, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (531, 531, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (532, 532, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (533, 533, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (534, 534, 23);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (535, 535, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (536, 536, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (537, 537, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (538, 538, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (539, 539, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (540, 540, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (541, 541, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (542, 542, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (543, 543, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (544, 544, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (545, 545, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (546, 546, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (547, 547, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (548, 548, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (549, 549, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (550, 550, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (551, 551, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (552, 552, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (553, 553, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (554, 554, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (555, 555, 16);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (556, 556, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (557, 557, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (558, 558, 19);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (559, 559, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (560, 560, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (561, 561, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (562, 562, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (563, 563, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (564, 564, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (565, 565, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (566, 566, 6);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (567, 567, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (568, 568, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (569, 569, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (570, 570, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (571, 571, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (572, 572, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (573, 573, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (574, 574, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (575, 575, 14);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (576, 576, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (577, 577, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (578, 578, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (579, 579, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (580, 580, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (581, 581, 17);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (582, 582, 11);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (583, 583, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (584, 584, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (585, 585, 5);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (586, 586, 12);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (587, 587, 4);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (588, 588, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (589, 589, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (590, 590, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (591, 591, 2);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (592, 592, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (593, 593, 9);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (594, 594, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (595, 595, 1);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (596, 596, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (597, 597, 7);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (598, 598, 8);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (599, 599, 3);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (600, 600, 19);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (601, NULL, 50);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (602, NULL, 25);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (603, NULL, 148);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (604, NULL, 73);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (605, NULL, 153);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (606, NULL, 132);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (607, NULL, 22);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (608, NULL, 19);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (609, NULL, 47);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (610, NULL, 22);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (611, NULL, 64);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (612, NULL, 225);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (613, NULL, 115);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (614, NULL, 28);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (615, NULL, 80);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (616, NULL, 124);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (617, NULL, 77);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (618, NULL, 16);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (619, NULL, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (620, NULL, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (621, NULL, 107);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (622, NULL, 147);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (623, NULL, 190);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (624, NULL, 15);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (625, NULL, 80);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (626, NULL, 235);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (627, NULL, 150);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (628, NULL, 133);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (629, NULL, 25);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (630, NULL, 20);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (631, NULL, 16);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (632, NULL, 246);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (633, NULL, 80);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (634, NULL, 134);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (635, NULL, 111);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (636, NULL, 12);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (637, NULL, 11);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (638, NULL, 71);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (639, NULL, 32);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (640, NULL, 75);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (641, NULL, 22);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (642, NULL, 153);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (643, NULL, 79);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (644, NULL, 36);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (645, NULL, 64);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (646, NULL, 74);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (647, NULL, 66);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (648, NULL, 122);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (649, NULL, 27);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (650, NULL, 58);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (651, NULL, 38);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (652, NULL, 75);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (653, NULL, 46);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (654, NULL, 59);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (655, NULL, 46);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (656, NULL, 66);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (657, NULL, 61);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (658, NULL, 230);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (659, NULL, 20);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (660, NULL, 108);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (661, NULL, 16);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (662, NULL, 57);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (663, NULL, 147);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (664, NULL, 88);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (665, NULL, 130);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (666, NULL, 58);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (667, NULL, 25);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (668, NULL, 23);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (669, NULL, 229);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (670, NULL, 135);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (671, NULL, 23);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (672, NULL, 205);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (673, NULL, 12);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (674, NULL, 13);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (675, NULL, 15);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (676, NULL, 15);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (677, NULL, 12);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (678, NULL, 59);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (679, NULL, 31);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (680, NULL, 30);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (681, NULL, 22);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (682, NULL, 51);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (683, NULL, 99);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (684, NULL, 36);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (685, NULL, 22);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (686, NULL, 178);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (687, NULL, 79);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (688, NULL, 116);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (689, NULL, 50);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (690, NULL, 22);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (691, NULL, 24);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (692, NULL, 70);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (693, NULL, 52);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (694, NULL, 47);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (695, NULL, 13);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (696, NULL, 61);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (697, NULL, 38);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (698, NULL, 13);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (699, NULL, 129);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (700, NULL, 165);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (701, NULL, 18);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (702, NULL, 124);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (703, NULL, 80);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (704, NULL, 25);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (705, NULL, 172);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (706, NULL, 64);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (707, NULL, 13);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (708, NULL, 12);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (709, NULL, 21);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (710, NULL, 27);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (711, NULL, 31);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (712, NULL, 153);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (713, NULL, 30);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (714, NULL, 29);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (715, NULL, 87);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (716, NULL, 35);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (717, NULL, 74);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (718, NULL, 227);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (719, NULL, 138);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (720, NULL, 12);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (721, NULL, 125);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (722, NULL, 24);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (723, NULL, 229);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (724, NULL, 175);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (725, NULL, 11);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (726, NULL, 60);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (727, NULL, 56);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (728, NULL, 70);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (729, NULL, 14);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (730, NULL, 149);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (731, NULL, 68);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (732, NULL, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (733, NULL, 15);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (734, NULL, 77);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (735, NULL, 161);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (736, NULL, 20);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (737, NULL, 54);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (738, NULL, 23);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (739, NULL, 174);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (740, NULL, 95);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (741, NULL, 20);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (742, NULL, 73);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (743, NULL, 21);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (744, NULL, 64);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (745, NULL, 15);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (746, NULL, 49);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (747, NULL, 79);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (748, NULL, 12);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (749, NULL, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (750, NULL, 148);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (751, NULL, 101);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (752, NULL, 107);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (753, NULL, 22);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (754, NULL, 13);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (755, NULL, 128);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (756, NULL, 130);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (757, NULL, 72);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (758, NULL, 71);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (759, NULL, 22);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (760, NULL, 54);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (761, NULL, 23);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (762, NULL, 25);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (763, NULL, 71);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (764, NULL, 19);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (765, NULL, 137);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (766, NULL, 44);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (767, NULL, 23);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (768, NULL, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (769, NULL, 18);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (770, NULL, 79);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (771, NULL, 24);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (772, NULL, 78);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (773, NULL, 33);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (774, NULL, 25);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (775, NULL, 25);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (776, NULL, 14);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (777, NULL, 101);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (778, NULL, 151);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (779, NULL, 120);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (780, NULL, 84);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (781, NULL, 58);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (782, NULL, 41);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (783, NULL, 24);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (784, NULL, 73);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (785, NULL, 23);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (786, NULL, 30);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (787, NULL, 52);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (788, NULL, 28);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (789, NULL, 16);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (790, NULL, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (791, NULL, 121);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (792, NULL, 24);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (793, NULL, 53);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (794, NULL, 50);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (795, NULL, 17);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (796, NULL, 127);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (797, NULL, 25);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (798, NULL, 39);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (799, NULL, 30);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (800, NULL, 21);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (801, NULL, 19);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (802, NULL, 65);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (803, NULL, 19);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (804, NULL, 45);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (805, NULL, 31);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (806, NULL, 34);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (807, NULL, 41);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (808, NULL, 75);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (809, NULL, 154);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (810, NULL, 38);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (811, NULL, 51);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (812, NULL, 168);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (813, NULL, 97);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (814, NULL, 14);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (815, NULL, 71);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (816, NULL, 63);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (817, NULL, 51);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (818, NULL, 149);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (819, NULL, 159);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (820, NULL, 155);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (821, NULL, 274);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (822, NULL, 32);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (823, NULL, 32);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (824, NULL, 37);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (825, NULL, 75);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (826, NULL, 76);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (827, NULL, 77);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (828, NULL, 36);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (829, NULL, 52);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (830, NULL, 42);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (831, NULL, 46);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (832, NULL, 22);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (833, NULL, 17);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (834, NULL, 28);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (835, NULL, 12);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (836, NULL, 18);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (837, NULL, 71);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (838, NULL, 33);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (839, NULL, 141);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (840, NULL, 15);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (841, NULL, 21);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (842, NULL, 17);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (843, NULL, 12);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (844, NULL, 26);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (845, NULL, 119);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (846, NULL, 21);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (847, NULL, 34);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (848, NULL, 62);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (849, NULL, 131);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (850, NULL, 31);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (851, NULL, 19);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (852, NULL, 30);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (853, NULL, 64);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (854, NULL, 44);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (855, NULL, 15);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (856, NULL, 70);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (857, NULL, 72);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (858, NULL, 108);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (859, NULL, 25);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (860, NULL, 65);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (861, NULL, 76);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (862, NULL, 153);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (863, NULL, 56);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (864, NULL, 79);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (865, NULL, 16);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (866, NULL, 74);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (867, NULL, 64);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (868, NULL, 14);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (869, NULL, 79);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (870, NULL, 31);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (871, NULL, 35);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (872, NULL, 63);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (873, NULL, 50);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (874, NULL, 54);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (875, NULL, 62);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (876, NULL, 53);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (877, NULL, 46);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (878, NULL, 44);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (879, NULL, 82);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (880, NULL, 75);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (881, NULL, 138);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (882, NULL, 123);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (883, NULL, 80);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (884, NULL, 76);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (885, NULL, 159);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (886, NULL, 37);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (887, NULL, 43);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (888, NULL, 62);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (889, NULL, 154);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (890, NULL, 13);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (891, NULL, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (892, NULL, 32);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (893, NULL, 55);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (894, NULL, 114);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (895, NULL, 21);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (896, NULL, 61);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (897, NULL, 17);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (898, NULL, 22);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (899, NULL, 63);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (900, NULL, 146);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (901, NULL, 33);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (902, NULL, 43);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (903, NULL, 32);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (904, NULL, 46);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (905, NULL, 127);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (906, NULL, 21);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (907, NULL, 13);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (908, NULL, 230);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (909, NULL, 153);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (910, NULL, 147);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (911, NULL, 14);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (912, NULL, 113);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (913, NULL, 70);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (914, NULL, 39);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (915, NULL, 40);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (916, NULL, 52);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (917, NULL, 12);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (918, NULL, 18);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (919, NULL, 89);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (920, NULL, 26);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (921, NULL, 123);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (922, NULL, 285);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (923, NULL, 149);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (924, NULL, 16);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (925, NULL, 211);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (926, NULL, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (927, NULL, 93);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (928, NULL, 17);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (929, NULL, 44);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (930, NULL, 65);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (931, NULL, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (932, NULL, 30);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (933, NULL, 293);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (934, NULL, 165);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (935, NULL, 19);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (936, NULL, 51);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (937, NULL, 39);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (938, NULL, 22);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (939, NULL, 61);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (940, NULL, 70);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (941, NULL, 79);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (942, NULL, 80);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (943, NULL, 25);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (944, NULL, 34);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (945, NULL, 114);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (946, NULL, 50);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (947, NULL, 44);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (948, NULL, 100);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (949, NULL, 70);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (950, NULL, 21);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (951, NULL, 27);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (952, NULL, 62);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (953, NULL, 11);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (954, NULL, 49);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (955, NULL, 28);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (956, NULL, 143);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (957, NULL, 29);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (958, NULL, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (959, NULL, 46);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (960, NULL, 68);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (961, NULL, 40);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (962, NULL, 24);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (963, NULL, 103);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (964, NULL, 63);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (965, NULL, 44);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (966, NULL, 21);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (967, NULL, 138);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (968, NULL, 15);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (969, NULL, 16);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (970, NULL, 150);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (971, NULL, 75);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (972, NULL, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (973, NULL, 79);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (974, NULL, 18);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (975, NULL, 47);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (976, NULL, 43);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (977, NULL, 115);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (978, NULL, 145);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (979, NULL, 35);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (980, NULL, 37);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (981, NULL, 18);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (982, NULL, 11);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (983, NULL, 127);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (984, NULL, 22);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (985, NULL, 42);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (986, NULL, 252);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (987, NULL, 44);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (988, NULL, 65);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (989, NULL, 139);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (990, NULL, 74);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (991, NULL, 63);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (992, NULL, 18);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (993, NULL, 240);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (994, NULL, 25);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (995, NULL, 10);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (996, NULL, 225);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (997, NULL, 22);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (998, NULL, 60);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (999, NULL, 25);

INSERT INTO LAGER (LAGERID, BESTELLUNGID, MENGE_VERFUEGBAR)
VALUES (1000, NULL, 51);

COMMIT;