-- ============================================================
-- Datei: lieferant_produkt_insert_simis1.sql
-- Zweck: Zuordnungen fuer Tabelle LIEFERANT_PRODUKT
-- Anzahl Zuordnungen: 209
-- Format: Einzel-INSERTs (SQL*Plus kompatibel)
-- Tabelle: LIEFERANT_PRODUKT(LIEFERANTID, PRODUKTID)
-- ============================================================

-- Optional: Tabelle leeren (nur ausfuehren, wenn gewuenscht)
-- DELETE FROM LIEFERANT_PRODUKT;
-- COMMIT;

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 6);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 8);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 9);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 10);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 11);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 12);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 17);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 18);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 19);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 20);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 21);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 22);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 23);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 24);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 25);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 26);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 27);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 28);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 29);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 30);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 31);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 32);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 33);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 34);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 35);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 36);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 44);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 51);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 52);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 53);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 54);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 57);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 58);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 59);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 60);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 61);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 62);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 63);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 64);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 65);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 66);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (1, 69);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (2, 5);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (2, 6);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (2, 7);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (2, 8);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (2, 51);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (2, 52);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (3, 1);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (3, 2);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (3, 3);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (3, 4);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (3, 13);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (3, 14);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (3, 15);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (3, 16);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (3, 27);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (3, 49);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (3, 50);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (3, 55);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (3, 56);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (3, 65);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (4, 9);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (4, 10);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (4, 39);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (4, 54);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (4, 63);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (5, 9);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (5, 10);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (5, 11);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (5, 12);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (5, 32);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (5, 33);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (5, 34);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (5, 35);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (5, 36);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (5, 53);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (5, 54);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (5, 66);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (6, 41);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (6, 42);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (6, 43);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (6, 44);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (6, 69);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (6, 70);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 14);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 16);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 18);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 19);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 21);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 25);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 28);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 29);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 30);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 31);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 32);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 36);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 37);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 38);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 39);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 40);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 41);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 42);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 43);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 44);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 57);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 59);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 63);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 64);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 67);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 68);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 69);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (7, 70);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (8, 37);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (8, 38);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (8, 39);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (8, 40);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (8, 67);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (8, 68);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 1);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 2);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 3);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 4);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 5);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 6);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 7);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 8);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 13);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 14);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 15);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 16);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 45);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 46);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 47);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 48);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 49);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 50);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 51);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 52);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 55);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 56);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 71);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (9, 72);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (10, 1);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (10, 4);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (10, 14);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (10, 15);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (10, 16);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (10, 45);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (10, 47);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (10, 48);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (10, 50);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (10, 55);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (10, 56);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (11, 29);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (11, 30);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (11, 31);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (11, 32);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (11, 63);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (11, 64);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (12, 17);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (12, 18);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (12, 19);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (12, 20);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (12, 21);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (12, 22);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (12, 23);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (12, 24);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (12, 25);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (12, 26);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (12, 27);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (12, 28);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (12, 37);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (12, 57);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (12, 58);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (12, 59);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (12, 60);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (12, 61);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (12, 62);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (13, 9);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (13, 12);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (13, 18);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (13, 21);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (13, 22);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (13, 23);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (13, 24);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (13, 25);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (13, 26);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (13, 27);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (13, 28);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (13, 34);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (13, 36);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (13, 57);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (13, 58);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (13, 59);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (13, 60);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (13, 62);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (14, 37);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (14, 38);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (14, 39);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (14, 40);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (14, 67);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (14, 68);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (15, 45);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (15, 46);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (15, 47);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (15, 48);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (15, 71);

INSERT INTO LIEFERANT_PRODUKT (LIEFERANTID, PRODUKTID)
VALUES (15, 72);

COMMIT;