-- ============================================================
-- Datei: produkt_insert_simis1.sql
-- Zweck: Hochwertige Beispieldaten fuer Tabelle PRODUKT (Premium-Moebelhaus)
-- Hinweis: Keine Sonderzeichen (Umlaute/ss). AKTIV: 'Y'/'N'
-- ============================================================

-- Optional: Tabelle leeren (nur ausfuehren, wenn gewuenscht)
-- DELETE FROM PRODUKT;
-- COMMIT;

INSERT ALL
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (1, 7, 1, 'Y', 'Leder Ecksofa Milano XL', 7999.00, 'Grosses Ecksofa aus vollnarbigem Leder, Federkern, Stahlfuesse, modulare Elemente.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (2, NULL, 1, 'Y', 'Designer Sessel Torino', 2499.00, 'Einzelsessel mit drehbarer Basis, Premiumleder, ergonomische Polsterung, handvernaehte Naehte.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (3, NULL, 1, 'Y', '2.5-Sitzer Sofa Siena', 5699.00, 'Kompaktes Luxussofa mit Daunenmix-Kissen, Massivholzrahmen, Bezugsstoff in Boucle.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (4, NULL, 1, 'Y', 'Relaxliege Capri', 3199.00, 'Verstellbare Relaxliege mit Kopfstuetze, weiche Polsterung, pulverbeschichtetes Gestell.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (5, 7, 2, 'Y', 'Boxspringbett Royal 180x200', 10999.00, 'High-End Boxspringbett mit Taschenfederkern, Topper, gepolstertes Kopfteil, Hotelkomfort.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (6, NULL, 2, 'Y', 'Massivholzbett Eiche Natur 160x200', 6799.00, 'Rahmen aus Eiche massiv, geoelte Oberflaeche, stabile Konstruktion, zeitloses Design.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (7, NULL, 2, 'Y', 'Kaltschaummatratze Premium 90x200', 1899.00, '7-Zonen Kaltschaum, atmungsaktiver Bezug, hohe Punktelastizitaet, fuer anspruchsvollen Schlaf.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (8, NULL, 2, 'Y', 'Latexmatratze Deluxe 180x200', 3999.00, 'Naturlatex Kern, sehr gute Klimaregulation, hohe Dauerelastizitaet, abnehmbarer Bezug.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (9, 2, 3, 'Y', 'Esstisch Nussbaum 240', 7499.00, 'Esstisch aus Nussbaum massiv, geoelte Platte, schlanke Metallkufen, fuer 8 bis 10 Personen.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (10, 12, 3, 'Y', 'Couchtisch Marmor Carrara', 2899.00, 'Couchtisch mit Marmorplatte, abgerundete Kanten, Untergestell aus gebuerstetem Metall.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (11, 2, 3, 'Y', 'Ausziehtisch Keramik 200-280', 6299.00, 'Ausziehbarer Tisch mit Keramikoberflaeche, kratzfest, Synchronauszug, leicht zu pflegen.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (12, NULL, 3, 'Y', 'Beistelltisch Messing Oval', 1299.00, 'Eleganter Beistelltisch, Messingfinish, stabile Basis, passt zu modernen Wohnbereichen.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (13, NULL, 4, 'Y', 'Esszimmerstuhl Leder Classic', 899.00, 'Stuhl mit Lederbezug, Massivholzgestell, komfortable Polsterung, fuer lange Abende.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (14, NULL, 4, 'Y', 'Freischwinger Premium', 799.00, 'Freischwinger mit Stahlrahmen, hochwertiger Stoffbezug, federnder Sitzkomfort.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (15, NULL, 4, 'Y', 'Design Bank 200', 2199.00, 'Sitzbank fuer Esstisch, Massivholz und Polster, klare Linien, sehr stabil.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (16, NULL, 4, 'Y', 'Barstuhl Leder High', 649.00, 'Barstuhl mit Hoehenverstellung, Leder, Fussstuetze, standsichere Basis.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (17, 7, 5, 'Y', 'Kleiderschrank Eiche 6-tuerig', 12499.00, 'Grosszuegiger Kleiderschrank aus Eiche, Soft-Close, Innenausstattung flexibel, Premiumbeschlaege.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (18, NULL, 5, 'Y', 'Sideboard Nussbaum 180', 5899.00, 'Sideboard mit Nussbaumfurnier, push-to-open, viel Stauraum, hochwertige Verarbeitung.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (19, NULL, 5, 'Y', 'Vitrine Glas und Stahl', 4499.00, 'Vitrine mit Sicherheitsglas, Stahlrahmen, integrierte Beleuchtung, ideal fuer Sammlerstuecke.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (20, NULL, 5, 'Y', 'Kommode Lack matt 120', 3499.00, 'Kommode mit matter Lackoberflaeche, Schubladen mit Soft-Close, minimalistische Optik.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (21, NULL, 6, 'Y', 'TV Lowboard Premium 220', 3999.00, 'Lowboard mit Kabelmanagement, push-to-open, robuste Oberflaeche, fuer grosse TVs.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (22, 9, 6, 'Y', 'Wohnwand Modular Set', 8999.00, 'Modulares Wohnwand-System, kombinierbare Elemente, verdeckte Aufhaengung, edle Fronten.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (23, NULL, 6, 'Y', 'Bibliothek Regalwand 300', 6799.00, 'Regalwand mit verstellbaren Boeden, Echtholzfurnier, integriertem Leiterprofil.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (24, NULL, 6, 'Y', 'Kaminholzregal Design', 1599.00, 'Offenes Regal fuer Kaminholz, Stahlrahmen, stabile Ablage, modernes Statement.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (25, NULL, 7, 'Y', 'Nachttisch Set Eiche', 1799.00, 'Zwei Nachttische aus Eiche, Schublade mit Soft-Close, schwebende Optik.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (26, NULL, 7, 'Y', 'Schminktisch Luxus', 2799.00, 'Schminktisch mit Spiegel, Schubladen, integrierter Beleuchtung, samtige Oberflaeche.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (27, NULL, 7, 'Y', 'Bettbank Leder 160', 2199.00, 'Bettbank mit Lederpolster, Metallgestell, elegante Sitzflaeche, fuer Schlafzimmerende.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (28, NULL, 7, 'Y', 'Kleiderschrank Innenausstattung Set', 1499.00, 'Set aus Schubladen, Kleiderstangen und Boxen, passend fuer modulare Schraenke.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (29, NULL, 8, 'Y', 'Schreibtisch Massivholz 180', 3299.00, 'Schreibtisch aus Massivholz, Kabelkanal, stabile Beine, fuer Homeoffice auf Premium-Niveau.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (30, NULL, 8, 'Y', 'Ergonomischer Buerostuhl Executive', 1599.00, 'Buerostuhl mit Synchronmechanik, Lordosenstuetze, Leder, hohe Tragkraft.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (31, NULL, 8, 'Y', 'Aktenschrank Metall Premium', 2499.00, 'Aktenschrank mit Schloss, pulverbeschichtet, leise Tueren, professionelle Optik.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (32, NULL, 8, 'Y', 'Meeting Tisch 240', 5999.00, 'Grosser Meetingtisch, robuste Platte, Metallgestell, fuer 6 bis 8 Personen.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (33, 7, 9, 'Y', 'Essgruppe Premium Set', 14999.00, 'Set aus Esstisch und 6 Stuehlen, abgestimmte Materialien, hochwertige Polster, sofort komplett.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (34, NULL, 9, 'Y', 'Kuecheninsel Regalmodul', 4799.00, 'Regalmodul fuer Kuecheninsel, Echtholzfronten, praktische Faecher, hochwertiges Finish.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (35, NULL, 9, 'Y', 'Highboard Esszimmer 160', 6399.00, 'Highboard mit Glasfronten, Beleuchtung, Soft-Close, viel Stauraum fuer Geschirr.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (36, NULL, 9, 'Y', 'Servierwagen Edelstahl', 1199.00, 'Servierwagen auf Rollen, Edelstahl und Holz, stabile Ablagen, fuer stilvolles Servieren.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (37, 10, 10, 'Y', 'Pendelleuchte Glas Trio', 1299.00, 'Pendelleuchte mit drei Glaskugeln, dimmbar, hochwertiger Baldachin, fuer Esstischzonen.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (38, NULL, 10, 'Y', 'Stehleuchte Designer Arc', 1899.00, 'Bogenleuchte mit schwerem Fuss, Stoffschirm, warmes Licht, eleganter Look.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (39, NULL, 10, 'Y', 'Wandleuchte Messing Pair', 899.00, 'Zwei Wandleuchten im Set, Messingfinish, indirektes Licht, passt zu Fluren und Wohnraum.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (40, NULL, 10, 'Y', 'Deckenleuchte LED Premium', 1599.00, 'LED Deckenleuchte mit hoher Farbwiedergabe, dimmbar, flaches Design, sehr effizient.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (41, 5, 11, 'Y', 'Outdoor Lounge Set Teak', 9999.00, 'Lounge Set aus Teak, wetterfeste Polster, modulare Elemente, fuer Terrasse und Garten.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (42, 5, 11, 'Y', 'Gartentisch Teak 220', 4599.00, 'Gartentisch aus Teak, stabil, geoelte Oberflaeche, fuer 8 Personen.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (43, NULL, 11, 'Y', 'Outdoor Sessel Rope', 1299.00, 'Outdoor Sessel mit Rope-Geflecht, Aluminiumrahmen, wetterfest, sehr komfortabel.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (44, 5, 11, 'Y', 'Sonnenliege Premium', 2199.00, 'Sonnenliege mit verstellbarer Rueckenlehne, wetterfeste Polster, Rollen, sehr robust.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (45, 10, 12, 'Y', 'Wollteppich Handgewebt 200x300', 2499.00, 'Handgewebter Wollteppich, dichtes Florbild, zeitlose Struktur, fuer gehobene Wohnbereiche.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (46, 8, 12, 'Y', 'Vorhang Samt Deluxe 2er Set', 799.00, 'Samtvorhaenge im Set, schwere Qualitaet, blickdicht, eleganter Fall.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (47, 10, 12, 'Y', 'Kissen Set Premium 4er', 299.00, 'Vier Dekokissen mit hochwertigen Bezuegen, unterschiedliche Texturen, abgestimmte Farben.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (48, 8, 12, 'Y', 'Plaid Kaschmir Mix', 349.00, 'Weiches Plaid aus Kaschmir-Mix, warm und leicht, edler Look fuer Sofa und Sessel.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (49, 1, 1, 'Y', 'Modulsofa Bellagio', 12999.00, 'Modulares Sofa mit flexiblen Elementen, Premiumstoff, Daunenmix, fuer grosszuegige Wohnraeume.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (50, 1, 1, 'Y', 'Recamiere Venezia', 2599.00, 'Recamiere mit eleganter Linienfuehrung, hochwertiger Stoffbezug, stabile Holzbasis.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (51, NULL, 2, 'Y', 'Polsterbett Velvet 140x200', 4999.00, 'Polsterbett mit samtigem Bezug, Lattenrost-Aufnahme, gepolstertes Kopfteil, hochwertig verarbeitet.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (52, NULL, 2, 'Y', 'Topper Gel Premium 180', 999.00, 'Gelschaum-Topper fuer 180er Bett, druckentlastend, atmungsaktiv, Bezug waschbar.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (53, NULL, 3, 'Y', 'Konferenztisch Eiche 320', 11999.00, 'Grosser Konferenztisch aus Eiche, robuste Platte, Kabeldurchlass, fuer 10 bis 12 Personen.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (54, NULL, 3, 'Y', 'Console Tisch Travertin', 2499.00, 'Schlanke Konsole mit Travertinplatte, Metallgestell, ideal fuer Flur oder Wohnzimmer.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (55, NULL, 4, 'Y', 'Esszimmer Drehstuhl Premium', 1099.00, 'Drehstuhl mit Rueckholmechanik, Polsterstoff, Armlehnen, komfortabel und stabil.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (56, NULL, 4, 'Y', 'Hocker Leder Stitch', 499.00, 'Kompakter Hocker mit Lederbezug, dekorative Naehte, vielseitig einsetzbar.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (57, NULL, 5, 'Y', 'Anrichte Eiche 240', 7999.00, 'Anrichte aus Eiche, Soft-Close, viel Stauraum, hochwertige Fronten und Beschlaege.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (58, NULL, 5, 'Y', 'Buecherregal Nussbaum 220', 5599.00, 'Regal aus Nussbaumfurnier, verstellbare Boeden, stabile Rueckwand, edle Optik.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (59, NULL, 6, 'Y', 'Couchtisch Set 2-teilig', 2199.00, 'Zwei Couchtische in abgestimmten Groessen, Metall und Holz, flexibel kombinierbar.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (60, NULL, 6, 'Y', 'Medienboard Lack 200', 3499.00, 'Medienboard mit Lackfront, Kabelmanagement, push-to-open, klare Linien.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (61, NULL, 7, 'Y', 'Kommode Schlafzimmer 160', 4799.00, 'Schlafzimmerkommode mit 6 Schubladen, Soft-Close, hochwertige Oberflaeche, viel Stauraum.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (62, NULL, 7, 'Y', 'Kopfteil Polster Premium 180', 1899.00, 'Gepolstertes Kopfteil fuer 180er Betten, strukturierter Stoff, wandmontierbar.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (63, NULL, 8, 'Y', 'Regalsystem Office Modular', 3299.00, 'Modulares Regalsystem fuer Buero, kombinierbare Elemente, Echtholzfurnier, sehr stabil.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (64, NULL, 8, 'Y', 'Steh-Sitz Tisch elektrisch', 2899.00, 'Elektrisch hoehenverstellbarer Tisch, leiser Motor, Memory-Funktion, hochwertige Platte.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (65, NULL, 9, 'Y', 'Esszimmerstuhl Set 6er Leder', 4999.00, 'Set aus 6 Lederstuehlen, stabile Gestelle, abgestimmte Polsterhaerte, fuer Esszimmer.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (66, NULL, 9, 'Y', 'Buffet Schrank 200', 8499.00, 'Buffet-Schrank mit Glas- und Holzfronten, Beleuchtung, Soft-Close, fuer Geschirr und Deko.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (67, 10, 10, 'Y', 'Tischleuchte Porzellan', 599.00, 'Tischleuchte mit Porzellanfuss, Stoffschirm, warmes Licht, hochwertige Verarbeitung.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (68, NULL, 10, 'Y', 'Schienensystem LED 5 Spots', 1199.00, 'LED Schienensystem mit 5 Spots, flexibel ausrichtbar, dimmbar, ideal fuer Akzentlicht.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (69, 5, 11, 'Y', 'Outdoor Essstuhl Set 6er', 4199.00, 'Set aus 6 Outdoor Essstuehlen, Aluminiumrahmen, wetterfestes Geflecht, pflegeleicht.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (70, NULL, 11, 'Y', 'Pergola Sonnenschutz Premium', 5999.00, 'Pergola mit verstellbaren Lamellen, robustes Aluminium, fuer hochwertigen Aussenschutz.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (71, 8, 12, 'Y', 'Teppich Premium 160x230', 699.00, 'Teppich mit dichtem Flor, pflegeleicht, elegante Struktur, fuer Wohn- und Schlafzimmer.')
  INTO PRODUKT (PRODUKTID, AKTIONID, KATEGORIEID, AKTIV, NAME, BASISPREIS, BESCHREIBUNG)
  VALUES (72, NULL, 12, 'Y', 'Leinenkissen 2er Set', 189.00, 'Leinenkissen im 2er Set, hochwertige Bezuege, angenehm griffig, dekorativ und zeitlos.')
SELECT 1 FROM DUAL;

COMMIT;
