-- Beispieldaten für Tabelle ZAHLUNGSART
-- Struktur laut Skript_SIMIS1.sql:
--   ZAHLUNGSARTID  NUMBER(20,0)  NOT NULL (PK)
--   BEZEICHNUNG    VARCHAR2(50)  NOT NULL

INSERT ALL
  INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (1,  'Kreditkarte')
  INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (2,  'Debitkarte')
  INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (3,  'PayPal')
  INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (4,  'Rechnung')
  INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (5,  'Vorkasse (Überweisung)')
  INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (6,  'SEPA-Lastschrift')
  INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (7,  'Sofortüberweisung')
  INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (8,  'Apple Pay')
  INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (9,  'Google Pay')
  INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (10, 'Barzahlung')
SELECT 1 FROM DUAL;

COMMIT;
