-- Auto-generiert für Oracle 19c basierend auf Skript_Simis_Neu.sql
-- Tabelle: ZAHLUNGSART
SET DEFINE OFF;

INSERT INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (1, 'Kreditkarte');
INSERT INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (2, 'Debitkarte');
INSERT INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (3, 'PayPal');
INSERT INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (4, 'Rechnung');
INSERT INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (5, 'Vorkasse (Überweisung);
INSERT INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (6, 'SEPA-Lastschrift');
INSERT INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (7, 'Sofortüberweisung');
INSERT INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (8, 'Apple Pay');
INSERT INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (9, 'Google Pay');
INSERT INTO ZAHLUNGSART (ZAHLUNGSARTID, BEZEICHNUNG) VALUES (10, 'Barzahlung');

COMMIT;